// app/layout.jsx
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from 'sonner'; // นำเข้า Toaster

// กำหนด Font
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// กำหนด Metadata
export const metadata = {
  title: "Project",
  description: "Generated by create next app",
};

// Component Layout หลัก (RootLayout)
export default function RootLayout({ children }) {
  return (
    // กำหนดภาษา, Font Variable และป้องกัน Hydration Warning
    <html lang="th" suppressHydrationWarning> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>

        {/* 1. เพิ่ม Toaster สำหรับแสดง Notification/Toast */}
        <Toaster richColors position="top-right" /> 
        
      </body>
    </html>
  );
}